---
#RHEL specific tasks
# msg: Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!
- name: Install libselinux-python
  yum:
    name: libselinux-python

- name: Import Oulyer package signing gpg key
  rpm_key:
    key: https://packages.outlyer.com/outlyer-pubkey.gpg
    state: present

- name: Outlyer Yum Repository
  yum_repository:
    name: outlyer
    description: Outlyer Agent repo
    baseurl: https://packages.outlyer.com/stable/el$releasever/$basearch/
    gpgcheck: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat'

- name: Outlyer Yum Repository
  yum_repository:
    name: outlyer
    description: Outlyer Agent repo
    baseurl: https://packages.outlyer.com/stable/el6/$basearch/
    gpgcheck: yes
  when: ansible_distribution == 'Amazon'
